### ISSUE TITLE
Module Attribute Error: "LightningControllableT5' object has no attribute 'processor'

### ISSUE THREAD

**Issue by Akshay0799** [nitaytech/DoCoGen#2]
When I try to train the models, the classifier gets trained initially, and when I the generator starts to train this error pops up:
Module Attribute Error: "LightningControllableT5" object has no attribute 'processor'

The object of the class 'Lightning Controllable T5' throws an error whenever 'self.processor' is referenced. I don't know if 'processor' is supposed to be inherited from the 'Controllable T5' class.

**Comment by UltramanQian** [comment]
Me too

**Comment by nitaytech** [comment]
Oh wow, thank you for pointing this out. 
I have fixed it (everything should work now, I have run the code on my machine).
