### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException

### ISSUE THREAD

**Issue by Akshay0799** [nitaytech/DoCoGen#3]
The generator trains now, but this error pops up when I try to train the T5Generator:

pytorch_lightning.utilities.exceptions.MisconfigurationException: ModelCheckpoint(monitor='validation_mean_generated_predict_acc') not found in the returned metrics: ['train_mean_loss', 'train_mean_mlm_loss', 'train_mean_predict_loss', 'train_mean_predict_acc', 'train_mean_predict_domain_loss', 'train_mean_predict_domain_acc']. HINT: Did you call self.log('validation_mean_generated_predict_acc', tensor) in the LightningModule?

**Comment by nitaytech** [comment]
Thank you.
I can't replicate this error, but as far as I know, these kinds of errors are bugs in PytorchLightning and the Exception is triggered when another Exception occurs (e.g. cuda out of memory).

Can you please copy-paste the whole log?

You can also try running the code again:
`conda env remove -n docogen_env  # for deleting the old env`
`git clone https://github.com/nitaytech/DoCoGen.git`
`cd DoCoGen`
`conda env create -f code/docogen_env.yml`
`conda activate docogen_env`
`unzip data/paper_data.zip -d data/`
`python code/main.py -c code/configs/reviews.json`

You can change some arguments in the configs file for a faster run (or for a smaller batch size) just to see if the code works for you (and if it doesn't, please share with me the logs):
"fast_dev": true,  # if you use true the dataset is subsampled, and only ~100 examples are used.
"project_dir": "experiments/reviews_debug",
"batch_size": 16,
"generator_epochs": 1,
"generator_classifier_epochs": 1,
"generator_classifier_batch_size": 16,


I hope it helps.

**Comment by Akshay0799** [comment]
> Thank you. I can't replicate this error, but as far as I know, these kinds of errors are bugs in PytorchLightning and the Exception is triggered when another Exception occurs (e.g. cuda out of memory).
> 
> Can you please copy-paste the whole log?
> 
> You can also try running the code again: `conda env remove -n docogen_env # for deleting the old env` `git clone https://github.com/nitaytech/DoCoGen.git` `cd DoCoGen` `conda env create -f code/docogen_env.yml` `conda activate docogen_env` `unzip data/paper_data.zip -d data/` `python code/main.py -c code/configs/reviews.json`
> 
> You can change some arguments in the configs file for a faster run (or for a smaller batch size) just to see if the code works for you (and if it doesn't, please share with me the logs): "fast_dev": true, # if you use true the dataset is subsampled, and only ~100 examples are used. "project_dir": "experiments/reviews_debug", "batch_size": 16, "generator_epochs": 1, "generator_classifier_epochs": 1, "generator_classifier_batch_size": 16,
> 
> I hope it helps.

Thank you !

It got resolved once I recreated the conda environment and tried it with a lesser batch size. The model finally finished training.
